### ISSUE TITLE
Curation Checklist

### ISSUE THREAD

**Issue by lmrodriguezr** [seq-code/registry#100]
The Registry should track
- [x] Implement scaffold for checks
- [x] Adapt `QcWarning` to support checks
- [x] Implement checklist system for manual curation
- [x] Separate checklists in nomenclatural and genomic
- [x] Implement all listed checks in `app/models/name/quality_checks.rb` (`nil`, `false`, `true`)
- [x] Track curator(s)
